### ISSUE TITLE
Colors not working out of the box

### ISSUE THREAD

**Issue by CMahaff** [tomasr/molokai#40]
Hi, bit of a vim noob here. I couldn't get your theme to work, but I could get a similar theme to work ["monokai"](https://github.com/sickill/vim-monokai/blob/master/colors/monokai.vim)

I found out the solution was to add

```
set t_Co=256
```

[This commit](https://github.com/sickill/vim-monokai/commit/f466b13b4ee0f067402afbee44739ef44a7ce93a) to monokai says that explicitly sets the colors to 256. I don't know if that would mess with vim desktop users or not, but it made it work for me and I do love the theme.

I'm running vim 7.4.52 in the terminal on Ubuntu 14.04.

**Comment by Bwahharharrr** [comment]
I just encountered the same error thanks for the fix
