### ISSUE TITLE
Incorrect highlight after `debug0`

### ISSUE THREAD

**Issue by Congee** [tomasr/molokai#48]
![screen shot 2015-04-03 at 12 18 09 pm](https://cloud.githubusercontent.com/assets/2083950/6977974/81c44982-d9fb-11e4-87f8-0a42620f4c88.png)
As you see...

**Comment by justinmk** [comment]
Has nothing to do with molokai. It may be a `syntax/c.vim` bug.

**Comment by Congee** [comment]
@justinmk thx :)
