### ISSUE TITLE
Support for truecolor mode in the terminal

### ISSUE THREAD

**Issue by chrisbra** [tomasr/molokai#66]
Hi,
I am just wondering, does this colorscheme support truecolor mode in the terminal (`:set termguicolors` in Vim)?

Thanks.

**Comment by justinmk** [comment]
Wouldn't that be a matter of removing the has(gui) conditions and merging all of the cterm/gui items? Anyways, the answer is no.

**Comment by chrisbra** [comment]
okay, thanks.
