### ISSUE TITLE
Cannot find color scheme "monokai"

### ISSUE THREAD

**Issue by ericat** [tomasr/molokai#71]
Possibly related to [#60](https://github.com/tomasr/molokai/issues/69)

The error happens when trying to source the .vimrc from vim itself with this command:
```
:source $MYVIMRC
```

Can you help?

<img width="716" alt="screen shot 2017-12-30 at 16 45 05" src="https://user-images.githubusercontent.com/2279048/34461374-11875ba2-ee28-11e7-946d-f881e50107b7.png">

**Comment by ghost** [comment]
Hi ericat,

I think you mispelt the color scheme in your .vimrc.  It should be "molokai", not "monokai".

`colorscheme molokai`

Also, at the very bottom of the README on my [dotfiles](https://github.com/brianrthompson/dotfiles/blob/master/.vimrc) repo there is a simple set of commands you can use if you're still having issues.

**Comment by ericat** [comment]
@brianrthompson thanks for the reply, I am fairly sure I have the same .vimrc settings on two machines - only causing troubles on one :(

Closing for now, will take a look in the evening.

**Comment by GangLongYu** [comment]
cp .vim/bundle/molokai/colors/ .vim -r
