### ISSUE TITLE
molokai seems not work

### ISSUE THREAD

**Issue by fanux** [tomasr/molokai#76]
![image](https://user-images.githubusercontent.com/8912557/53789273-05027180-3f5f-11e9-953c-1769e98eff77.png)

my .vimrc:
```
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'L9'
Plugin 'fatih/vim-go'
Bundle 'scrooloose/nerdtree'
Plugin 'Valloric/YouCompleteMe'
Plugin 'vim-scripts/taglist.vim'
Plugin 'tomasr/molokai'
call vundle#end() 

let g:molokai_original = 1
let g:rehash256 = 1
set sw=4

" colorscheme molokai
```

I build vim from source and run it in docker...   On my mac it work correctly

**Comment by der-swing** [comment]
Wait, you commented out the last line, where the colorscheme should be set to molokai? 
Maybe overstating the obvious here, but shouldn't you remove the double quote in the last line?

**Comment by fanux** [comment]
Oh... my mistake
